spring:
  profiles:
    active:
    - dog
    - ES
    - prod
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcUrl: YmlUrlForDB

---
spring:
  config:
    activate:
      on-profile: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcUrl: YmlProdUrlForDB
